# Build Stage
FROM python:3.9.15-alpine AS builder

# Required to install mysqlclient with pip.
RUN apk update &&\
    apk add --virtual build-deps gcc python3-dev musl-dev &&\
    apk add --no-cache mariadb-dev

RUN pip install --upgrade pip

COPY /requirements/common.txt /requirements/dev.txt /requirements/

RUN pip install -r /requirements/dev.txt


# Run Stage
FROM python:3.9.15-alpine

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apk add bash

WORKDIR /app

COPY --from=builder /usr/local/lib/python3.9/site-packages/ /usr/local/lib/python3.9/site-packages/

COPY . /app
